### ISSUE TITLE
Support for android 4.4?

### ISSUE THREAD

**Issue by themronion** [roubachof/Sharpnado.Shadows#4]
Will your amazing package work with android 4.4? There is no elevation property there, so i got curious. Thanks for the future reply!

**Comment by roubachof** [comment]
Prerequisite for Android is RenderScript support so yes it should.

**Comment by themronion** [comment]
Amazing!! I'll try it tomorrow and let you know

**Comment by themronion** [comment]
Nope. Unfortunately 4.4 gave this error: Java.Lang.NoSuchMethodError: 'no method with name='drawRoundRect' signature='(FFFFFFLandroid/graphics/Paint;)V' in class Landroid/graphics/Canvas;' Is it fixable?

**Comment by themronion** [comment]
Found a tip for you: [https://stackoverflow.com/questions/53029725/how-to-draw-rounded-rectangle-in-api-level-below-21-on-a-canvas](url)

**Comment by roubachof** [comment]
Should be easy to fix since I could use an other method signature which is doing the same stuff and is available since api 1. Damn Android fragmentation!

**Comment by roubachof** [comment]
Maybe fork the project and create a pr

**Comment by themronion** [comment]
I am not so skilled, unfortunately) Take your time, it's not a hurry. Let me know when you'll fix it. And once again: amazing package!

**Comment by roubachof** [comment]
Ok just watch the issue, I will update It when it is fixed

Le sam. 27 juin 2020 à 11:53, Pavlo Lukianets <notifications@github.com> a
écrit :

**Comment by themronion** [comment]
I guess this
 `bitmapCanvas.DrawRoundRect(
                MaxRadius,
                MaxRadius,
                source.MeasuredWidth + MaxRadius,
                source.MeasuredHeight + MaxRadius,
                _cornerRadius,
                _cornerRadius,
                paint);`
 changes to--》
`RectF rect = new RectF(MaxRadius,
                MaxRadius,
                source.MeasuredWidth + MaxRadius,
                source.MeasuredHeight + MaxRadius);
bitmapCanvas.DrawRoundRect(
                rect,
                _cornerRadius,
                _cornerRadius,
                paint);`

**Comment by themronion** [comment]
Figured out how to fork and do a pull request. Check it out if everything is correct on your spare time

**Comment by roubachof** [comment]
Should be fixed by your PR #5

**Comment by themronion** [comment]
Yep, i downloaded the source files a day ago with my pr and it worked as planned) Waiting for the nuget)
